packages:
  - "frontend"
  - "backend"
allowBuilds:
  '0': '@parcel/watcher'
  '1': '@swc/core'
  '2': core-js
  '3': esbuild
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
